import "./env.js";

export const bookingConfig = {
  agency: {
    name: "Karthik Travels",
    city: "Coimbatore",
    address:
      "Chemical House, Old No: 18 - New No: 24, Bharathi Park 4th Cross Street, Near BSNL Office, Saibaba Colony, Coimbatore - 641 011, Tamil Nadu, India.",
  },
  cities: ["Pondicherry", "Coimbatore", "Tiruppur", "Ooty", "Erode"],
  passengers: [
    { id: "1", label: "1 person", min: 1, max: 1, vehicle: "Sedan / Dzire / Etios" },
    { id: "2", label: "2 people", min: 2, max: 2, vehicle: "Sedan / Dzire / Etios" },
    { id: "3", label: "3-4 people", min: 3, max: 4, vehicle: "Ertiga / Sedan" },
    { id: "4", label: "5-8 people", min: 5, max: 8, vehicle: "Innova / Innova Crysta / Tempo Traveller" },
    { id: "5", label: "More than 8 people", min: 9, max: null, vehicle: "Tempo Traveller / Mini Bus" },
  ],
  packages: [
    { id: "100", label: "100 km package", note: "Best for short city and nearby temple routes." },
    { id: "200", label: "200 km package", note: "Best for nearby outstation day trips." },
    { id: "full-day", label: "Full day package", note: "Best for sightseeing and flexible timing." },
    { id: "custom", label: "Custom trip", note: "Best for multi-stop or multi-day travel." },
  ],
  confirmations: ["Confirm booking", "Need more details", "Talk to owner", "Cancel"],
  rateCard: [
    {
      vehicle: "Toyota Etios",
      minimum: "3 hours",
      fare: "Rs.900",
      freeKm: "10 km",
      localExtraKm: "Rs.14/km",
      extraHour: "Rs.300/hour",
      plainsPackage: "Rs.3,100 - 100 km free",
      plainsExtraKm: "Rs.14/km",
      hillsPackage: "Rs.3,750 - 100 km free",
      hillsExtraKm: "Rs.15/km",
    },
    {
      vehicle: "Swift Dzire",
      minimum: "3 hours",
      fare: "Rs.900",
      freeKm: "10 km",
      localExtraKm: "Rs.14/km",
      extraHour: "Rs.300/hour",
      plainsPackage: "Rs.3,100 - 100 km free",
      plainsExtraKm: "Rs.14/km",
      hillsPackage: "Rs.3,750 - 100 km free",
      hillsExtraKm: "Rs.15/km",
    },
    {
      vehicle: "Toyota Innova",
      minimum: "3 hours",
      fare: "Rs.1,350",
      freeKm: "10 km",
      localExtraKm: "Rs.18/km",
      extraHour: "Rs.450/hour",
      plainsPackage: "Rs.4,800 - 100 km free",
      plainsExtraKm: "Rs.18/km",
      hillsPackage: "Rs.5,400 - 100 km free",
      hillsExtraKm: "Rs.19/km",
    },
    {
      vehicle: "Innova Crysta",
      minimum: "3 hours",
      fare: "Rs.1,500",
      freeKm: "10 km",
      localExtraKm: "Rs.19/km",
      extraHour: "Rs.500/hour",
      plainsPackage: "Rs.5,400 - 100 km free",
      plainsExtraKm: "Rs.19/km",
      hillsPackage: "Rs.6,000 - 100 km free",
      hillsExtraKm: "Rs.20/km",
    },
    {
      vehicle: "A/C Tempo Traveller",
      minimum: "Day basis",
      fare: "Basic day only",
      freeKm: "-",
      localExtraKm: "-",
      extraHour: "-",
      plainsPackage: "Rs.5,500 - 100 km free",
      plainsExtraKm: "Rs.20/km",
      hillsPackage: "Rs.6,200 - 100 km free",
      hillsExtraKm: "Rs.22/km",
    },
    {
      vehicle: "Urbania",
      minimum: "Day basis",
      fare: "Basic day only",
      freeKm: "-",
      localExtraKm: "-",
      extraHour: "-",
      plainsPackage: "Rs.10,000 - 100 km free",
      plainsExtraKm: "Rs.28/km",
      hillsPackage: "Rs.10,500 - 100 km free",
      hillsExtraKm: "Rs.30/km",
    },
    {
      vehicle: "Coach 20 Seat Van",
      minimum: "Day basis",
      fare: "Basic day only",
      freeKm: "-",
      localExtraKm: "-",
      extraHour: "-",
      plainsPackage: "Rs.7,000 - 100 km free",
      plainsExtraKm: "Rs.22/km",
      hillsPackage: "Rs.7,500 - 100 km free",
      hillsExtraKm: "Rs.24/km",
    },
    {
      vehicle: "A/C Coach",
      minimum: "Day basis",
      fare: "Basic day only",
      freeKm: "-",
      localExtraKm: "-",
      extraHour: "-",
      plainsPackage: "Rs.13,500 - 100 km free",
      plainsExtraKm: "Rs.38/km",
      hillsPackage: "Rs.13,500 - 100 km free",
      hillsExtraKm: "Rs.34/km",
    },
    {
      vehicle: "Tempo Traveller 18 Seat",
      minimum: "Day basis",
      fare: "Basic day only",
      freeKm: "-",
      localExtraKm: "-",
      extraHour: "-",
      plainsPackage: "Rs.6,200 - 100 km free",
      plainsExtraKm: "Rs.22/km",
      hillsPackage: "Rs.7,600 - 100 km free",
      hillsExtraKm: "Rs.24/km",
    },
  ],
  bookingDisclaimer: [
    "Starting km and time are calculated office-to-office.",
    "Toll and parking charges are extra.",
    "Other-state permit and tax charges are extra.",
    "Booking is confirmed only after 50% advance payment.",
    "After the trip/program is closed, the balance amount must be paid immediately.",
    "If an original GST bill is required, 5% GST is extra on the total amount.",
  ],
  owner: {
    whatsapp: process.env.OWNER_WHATSAPP_NUMBER || "",
    email: process.env.OWNER_EMAIL || "",
  },
  business: {
    whatsapp: process.env.BUSINESS_WHATSAPP_NUMBER || "",
    phone: process.env.BUSINESS_PHONE_NUMBER || "",
    email: process.env.BUSINESS_EMAIL || "",
  },
  templates: {
    greeting:
      "Vanakkam! Welcome to Karthik Travels. I can help you plan your trip in a few quick steps.",
    cityPrompt: "Please choose your pickup city:",
    passengerPrompt: "How many passengers will travel?",
    packagePrompt: "Please choose the package or pricing type you want:",
    confirmationPrompt: "Please confirm how you would like to continue:",
  },
};

export function publicConfig() {
  return {
    businessWhatsAppNumber: bookingConfig.business.whatsapp,
    businessPhoneNumber: bookingConfig.business.phone,
    businessEmail: bookingConfig.business.email,
    agencyName: bookingConfig.agency.name,
    bookingMessage: "Hi, I want to book a trip.",
  };
}
